In [2]:
import sqlite3
import pandas as pd

# Connect to SQLite database
conn = sqlite3.connect("Data/test.db")

# Read data from CSV file using pandas
csv_file = "Data/Base.csv"
df = pd.read_csv(csv_file)

df

,fraud_bool,income,name_email_similarity,prev_address_months_count,current_address_months_count,customer_age,days_since_request,intended_balcon_amount,payment_type,zip_count_4w,...,has_other_cards,proposed_credit_limit,foreign_request,source,session_length_in_minutes,device_os,keep_alive_session,device_distinct_emails_8w,device_fraud_count,month
0,1,0.9,0.166828,-1,88,50,0.020925,-1.331345,AA,769,...,0,500.0,0,INTERNET,3.888115,windows,0,1,0,7
1,1,0.9,0.296286,-1,144,50,0.005418,-0.816224,AB,366,...,0,1500.0,0,INTERNET,31.798819,windows,0,1,0,7
2,1,0.9,0.044985,-1,132,40,3.108549,-0.755728,AC,870,...,0,200.0,0,INTERNET,4.728705,other,0,1,0,7
3,1,0.9,0.159511,-1,22,50,0.019079,-1.205124,AB,810,...,1,200.0,0,INTERNET,2.047904,linux,0,1,0,7
4,1,0.9,0.596414,-1,218,50,0.004441,-0.773276,AB,890,...,0,1500.0,0,INTERNET,3.775225,macintosh,1,1,0,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,0,0.6,0.192631,-1,104,40,0.030592,-1.044454,AB,804,...,0,200.0,0,INTERNET,8.511502,linux,1,1,0,4
999996,0,0.8,0.322989,148,9,50,1.628119,-1.409803,AC,3306,...,0,200.0,0,INTERNET,8.967865,windows,0,1,0,4
999997,0,0.8,0.879403,-1,30,20,0.018563,34.692760,AA,1522,...,0,200.0,0,INTERNET,8.195531,other,0,1,0,4
999998,0,0.9,0.762112,-1,189,20,0.015352,94.661055,AA,1418,...,0,500.0,0,INTERNET,4.336064,windows,1,1,0,4
999999,0,0.2,0.697452,-1,321,20,2.655916,9.908499,AA,951,...,0,200.0,0,INTERNET,6.717022,linux,0,1,0,4

In [3]:
# Export DataFrame to SQLite database
table_name = "Raw_data"
df.to_sql(table_name, conn, if_exists="replace", index=False)

# Close the database connection
conn.close()

In [10]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("Data/test.db")

data_table = 'Raw_data'

sample_size = 11_000
# Retrieve data from the database
query = f"""
    SELECT *
    FROM {data_table}
    WHERE fraud_bool = ?
"""

fraud_true = pd.read_sql_query(query, conn, params=[True]).sample(n=sample_size, random_state=42).reset_index(drop=True)
fraud_false = pd.read_sql_query(query, conn, params=[False]).sample(n=sample_size, random_state=42).reset_index(drop=True)

# Close the database connection
conn.close()

In [16]:
# fraud_false = fraud_false.reset_index(drop=True)
fraud_false

,fraud_bool,income,name_email_similarity,prev_address_months_count,current_address_months_count,customer_age,days_since_request,intended_balcon_amount,payment_type,zip_count_4w,...,has_other_cards,proposed_credit_limit,foreign_request,source,session_length_in_minutes,device_os,keep_alive_session,device_distinct_emails_8w,device_fraud_count,month
0,0,0.9,0.162316,128,15,40,0.008528,-0.996048,AB,904,...,0,500.0,0,INTERNET,6.265841,windows,1,1,0,6
1,0,0.1,0.014232,101,3,40,0.001605,-0.771460,AB,1560,...,0,1000.0,0,INTERNET,4.737900,linux,0,1,0,6
2,0,0.1,0.556928,-1,60,50,0.030090,-0.471550,AB,1095,...,0,200.0,0,INTERNET,14.005306,other,1,1,0,2
3,0,0.9,0.425115,95,51,30,3.312687,51.680454,AA,1691,...,0,200.0,0,INTERNET,2.437244,other,0,1,0,2
4,0,0.8,0.060218,12,6,50,0.037293,-1.009755,AB,632,...,0,200.0,0,INTERNET,2.821325,other,0,1,0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10995,0,0.9,0.179859,-1,40,40,0.013248,-1.428670,AC,1327,...,0,200.0,0,INTERNET,8.161761,windows,1,1,0,5
10996,0,0.6,0.440915,10,30,30,0.000721,-0.705507,AB,2807,...,0,200.0,0,INTERNET,6.696032,other,1,1,0,1
10997,0,0.4,0.878585,-1,48,30,0.009767,-1.704876,AB,2987,...,1,200.0,0,INTERNET,4.863865,linux,0,2,0,1
10998,0,0.8,0.883525,32,3,50,0.017006,-0.651779,AD,2646,...,0,200.0,0,INTERNET,20.821354,windows,0,1,0,2
10999,0,0.4,0.104954,-1,168,10,1.118987,15.881890,AA,1261,...,0,1500.0,0,INTERNET,18.398948,windows,1,1,0,1

In [17]:
fraud_true

,fraud_bool,income,name_email_similarity,prev_address_months_count,current_address_months_count,customer_age,days_since_request,intended_balcon_amount,payment_type,zip_count_4w,...,has_other_cards,proposed_credit_limit,foreign_request,source,session_length_in_minutes,device_os,keep_alive_session,device_distinct_emails_8w,device_fraud_count,month
0,1,0.1,0.806991,-1,97,60,0.015935,-0.634436,AB,3855,...,0,2000.0,0,INTERNET,7.544072,windows,1,2,0,0
1,1,0.9,0.148245,-1,50,30,0.010388,-1.536339,AD,2435,...,0,2000.0,0,INTERNET,8.085512,linux,0,1,0,3
2,1,0.4,0.994741,-1,17,50,0.021381,-0.352025,AC,2757,...,0,200.0,0,INTERNET,39.955535,windows,0,1,0,6
3,1,0.8,0.304634,-1,172,40,0.011190,-0.520358,AD,2549,...,0,200.0,0,INTERNET,56.239295,macintosh,1,1,0,5
4,1,0.9,0.043160,-1,180,40,0.014090,-1.340004,AD,1350,...,0,1500.0,0,INTERNET,4.587038,windows,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10995,1,0.4,0.432110,-1,59,50,0.013125,-0.761739,AC,3797,...,0,200.0,0,INTERNET,23.908961,linux,0,0,0,1
10996,1,0.6,0.002811,93,3,30,0.012120,-0.826704,AD,1264,...,0,200.0,0,INTERNET,3.738467,windows,0,1,0,2
10997,1,0.9,0.087533,102,21,30,0.024990,-1.178873,AC,1045,...,0,1500.0,1,INTERNET,2.027317,windows,0,1,0,3
10998,1,0.9,0.871551,-1,33,40,0.000770,-1.176693,AB,1075,...,0,1500.0,0,INTERNET,13.165603,windows,1,2,0,7
10999,1,0.2,0.171524,-1,227,40,0.010166,-1.060638,AC,2367,...,0,500.0,0,INTERNET,9.067779,windows,0,1,0,4

In [21]:
fraud_dataset = pd.concat((fraud_true, fraud_false),axis=0).reset_index(drop=True)
fraud_dataset.shape

(22000, 32)

In [22]:
fraud_dataset.fraud_bool.value_counts()

1    11000
0    11000
Name: fraud_bool, dtype: int64

In [48]:
fraud_true.fraud_bool.value_counts(), fraud_false.fraud_bool.value_counts()

(1    11000
 Name: fraud_bool, dtype: int64,
 0    11000
 Name: fraud_bool, dtype: int64)

In [22]:
df.payment_type.value_counts()

AB    370554
AA    258249
AC    252071
AD    118837
AE       289
Name: payment_type, dtype: int64

In [28]:
df.device_os.value_counts()

other        342728
linux        332712
windows      263506
macintosh     53826
x11            7228
Name: device_os, dtype: int64

In [29]:
df.dtypes

fraud_bool                            int64
income                              float64
name_email_similarity               float64
prev_address_months_count             int64
current_address_months_count          int64
customer_age                          int64
days_since_request                  float64
intended_balcon_amount              float64
payment_type                         object
zip_count_4w                          int64
velocity_6h                         float64
velocity_24h                        float64
velocity_4w                         float64
bank_branch_count_8w                  int64
date_of_birth_distinct_emails_4w      int64
employment_status                    object
credit_risk_score                     int64
email_is_free                         int64
housing_status                       object
phone_home_valid                      int64
phone_mobile_valid                    int64
bank_months_count                     int64
has_other_cards                       int64
proposed_credit_limit               float64
foreign_request                       int64
source                               object
session_length_in_minutes           float64
device_os                            object
keep_alive_session                    int64
device_distinct_emails_8w             int64
device_fraud_count                    int64
month                                 int64
dtype: object

In [32]:
categorical_columns = ['payment_type', 'employment_status', 'housing_status', 'source', 'device_os']

In [31]:
df.employment_status.value_counts()

CA    730252
CB    138288
CF     44034
CC     37758
CD     26522
CE     22693
CG       453
Name: employment_status, dtype: int64

In [34]:
df.housing_status.value_counts()

BC    372143
BB    260965
BA    169675
BE    169135
BD     26161
BF      1669
BG       252
Name: housing_status, dtype: int64

In [52]:
df[categorical_columns]

       payment_type employment_status housing_status    source  device_os
0                AA                CA             BA  INTERNET    windows
1                AB                CA             BA  INTERNET    windows
2                AC                CB             BA  INTERNET      other
3                AB                CA             BA  INTERNET      linux
4                AB                CA             BA  INTERNET  macintosh
...             ...               ...            ...       ...        ...
999995           AB                CA             BC  INTERNET      linux
999996           AC                CC             BC  INTERNET    windows
999997           AA                CF             BC  INTERNET      other
999998           AA                CA             BA  INTERNET    windows
999999           AA                CA             BE  INTERNET      linux

[1000000 rows x 5 columns]

In [54]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder


# Apply label encoding to the categorical column
le = LabelEncoder()
for col in categorical_columns:
    df[col] = le.fit_transform(df[col])

print(df[categorical_columns])

        payment_type  employment_status  housing_status  source  device_os
0                  0                  0               0       0          3
1                  1                  0               0       0          3
2                  2                  1               0       0          2
3                  1                  0               0       0          0
4                  1                  0               0       0          1
...              ...                ...             ...     ...        ...
999995             1                  0               2       0          0
999996             2                  2               2       0          3
999997             0                  5               2       0          2
999998             0                  0               0       0          3
999999             0                  0               4       0          0

[1000000 rows x 5 columns]

In [57]:
df.dtypes

fraud_bool                            int64
income                              float64
name_email_similarity               float64
prev_address_months_count             int64
current_address_months_count          int64
customer_age                          int64
days_since_request                  float64
intended_balcon_amount              float64
payment_type                          int64
zip_count_4w                          int64
velocity_6h                         float64
velocity_24h                        float64
velocity_4w                         float64
bank_branch_count_8w                  int64
date_of_birth_distinct_emails_4w      int64
employment_status                     int64
credit_risk_score                     int64
email_is_free                         int64
housing_status                        int64
phone_home_valid                      int64
phone_mobile_valid                    int64
bank_months_count                     int64
has_other_cards                       int64
proposed_credit_limit               float64
foreign_request                       int64
source                                int64
session_length_in_minutes           float64
device_os                             int64
keep_alive_session                    int64
device_distinct_emails_8w             int64
device_fraud_count                    int64
month                                 int64
dtype: object

In [33]:

import pandas as pd
import sqlite3



import pandas as pd
import sqlite3



### Step if no DB create db 

# Class Databse -> train, ref(valid), cur(test) dataset, database
class Database():

    def __init__(self):
        self.train_data, self.valid_ref_data, self.current_data = self.make_data()
        # pass
    
    def create_spl_DB_from_csv(self):
        """
        This will create DB to store raw data

        """
        # Connect to SQLite database
        conn = sqlite3.connect("Data/Fraud_database.db")
        
        # Read data from CSV file using pandas
        csv_file = "Data/Base.csv"
        df = pd.read_csv(csv_file)

        # Export DataFrame to SQLite database
        df.to_sql("Raw_data", conn, if_exists="replace", index=False)
        
        # clean the dataset
        df_clean = self.prepare_and_clean_dataset(df)
        
        # Export CLean Dataset to SQLite database
        df.to_sql("Clean_data", conn, if_exists="replace", index=False)
        
        conn.close()


    def prepare_and_clean_dataset(self, dataset):
        """
        This will clean the dataset 
        """
        categorical_columns = ['payment_type', 'employment_status', 'housing_status', 'source', 'device_os']
        import pandas as pd
        from sklearn.preprocessing import LabelEncoder


        # Apply label encoding to the categorical column
        le = LabelEncoder()
        for col in categorical_columns:
            dataset[col] = le.fit_transform(dataset[col])

        return dataset 
    
# ----------------------------------------------------- #
    def get_data_from_database(self):
        """
        this is the test hypothesis where 
        train, valid and current dataset become overlap
        then create main big file and split that
        where fraud_bool 0 and 1 is equal and random
        """
        
        conn = sqlite3.connect("Data/Fraud_database.db")
        # Create a cursor object
        cursor = conn.cursor()

        # Check if the table exists
        cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='Clean_data'")
        table_exists = cursor.fetchone()
        sample_size = 11_000
        query  = None

        if not table_exists:
            # If the table doesn't exist, call the create_sql_dataset function
            self.create_spl_DB_from_csv()
            
        else:
            # Retrieve data from the database
            query = f"""
                SELECT *
                FROM Clean_data
                WHERE fraud_bool = ?
            """

        fraud_true = pd.read_sql_query(query, conn, params=[True]).sample(n=sample_size, random_state=42).reset_index(drop=True)
        fraud_false = pd.read_sql_query(query, conn, params=[False]).sample(n=sample_size, random_state=42).reset_index(drop=True)

        # Close the database connection
        conn.close()
            
        return fraud_false, fraud_true
        
    def make_data(self):
        """
        Get data from DB to tain the model
        take : sql database(50% of database)
        output : df
        
        
        main data
            |
        #------------#
        |            |
    train     ref_current_data
                    |
              #-------------#
              |             |
           ref_Data      cur_Data
    
        """
        
        fraud_false, fraud_true = self.get_data_from_database()
        
        from sklearn.model_selection import train_test_split
        
        fraud_dataset = pd.concat((fraud_true, fraud_false), axis=0)
        
        train_data, ref_current_data = train_test_split(fraud_dataset, test_size = 0.5, random_state = 42)
        
        ref_data, current_data = train_test_split(ref_current_data, test_size = 0.5, random_state = 42)
        
        
        return train_data, ref_data, current_data
    

    
# ----------------------------------------------------- #

In [34]:
Database_website = Database()
Database_website

In [36]:
Database_website.train_data.shape

(11000, 32)

In [37]:
Database_website.valid_ref_data.shape

(5500, 32)

In [38]:
Database_website.current_data.shape

(5500, 32)

In [23]:
a, b, c = Database_website.make_data()

In [27]:
a.shape, a.fraud_bool.value_counts()

((11000, 32),
 0    5542
 1    5458
 Name: fraud_bool, dtype: int64)

In [28]:
b.shape, b.fraud_bool.value_counts()

((5500, 32),
 1    2791
 0    2709
 Name: fraud_bool, dtype: int64)

In [29]:
c.shape, c.fraud_bool.value_counts()

((5500, 32),
 1    2751
 0    2749
 Name: fraud_bool, dtype: int64)

In [40]:
from src.model import build_model

model = build_model()

model

{'Logistic Regression': LogisticRegression(),
 'Support Vector Classifier': SVC(),
 'Decision Tree': DecisionTreeClassifier(max_depth=6),
 'KNearest': KNeighborsClassifier(),
 'GaussianNB': GaussianNB(),
 'LDA': LinearDiscriminantAnalysis(),
 'Ridge': RidgeClassifier(),
 'QDA': QuadraticDiscriminantAnalysis(),
 'Bagging': BaggingClassifier(),
 'MLP': MLPClassifier(),
 'LSVC': LinearSVC(),
 'BernoulliNB': BernoulliNB(),
 'Passive_AC': PassiveAggressiveClassifier(),
 'SGB': GradientBoostingClassifier(random_state=9),
 'Adaboost': AdaBoostClassifier(learning_rate=0.8, n_estimators=100, random_state=9),
 'Extra_T': ExtraTreesClassifier(max_features=3),
 'R_forest': RandomForestClassifier(max_features=3, max_samples=0.9),
 'XGB': XGBClassifier(base_score=None, booster=None, callbacks=None,
               colsample_bylevel=None, colsample_bynode=None,
               colsample_bytree=None, early_stopping_rounds=None,
               enable_categorical=False, eval_metric=None, feature_types=None,
               gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
               interaction_constraints=None, learning_rate=0.05, max_bin=None,
               max_cat_threshold=None, max_cat_to_onehot=None,
               max_delta_step=None, max_depth=3, max_leaves=None,
               min_child_weight=None, missing=nan, monotone_constraints=None,
               n_estimators=300, n_jobs=None, num_parallel_tree=None,
               predictor=None, random_state=None, ...),
 'Stacking': StackingClassifier(cv=3,
                    estimators=[('RF',
                                 RandomForestClassifier(max_samples=0.9,
                                                        n_jobs=-1)),
                                ('knn', KNeighborsClassifier(n_jobs=-1))],
                    final_estimator=LogisticRegression(n_jobs=-1), n_jobs=-1,
                    passthrough=True)}

In [43]:
model.keys()

dict_keys(['Logistic Regression', 'Support Vector Classifier', 'Decision Tree', 'KNearest', 'GaussianNB', 'LDA', 'Ridge', 'QDA', 'Bagging', 'MLP', 'LSVC', 'BernoulliNB', 'Passive_AC', 'SGB', 'Adaboost', 'Extra_T', 'R_forest', 'XGB', 'Stacking'])

In [44]:
model.values()

dict_values([LogisticRegression(), SVC(), DecisionTreeClassifier(max_depth=6), KNeighborsClassifier(), GaussianNB(), LinearDiscriminantAnalysis(), RidgeClassifier(), QuadraticDiscriminantAnalysis(), BaggingClassifier(), MLPClassifier(), LinearSVC(), BernoulliNB(), PassiveAggressiveClassifier(), GradientBoostingClassifier(random_state=9), AdaBoostClassifier(learning_rate=0.8, n_estimators=100, random_state=9), ExtraTreesClassifier(max_features=3), RandomForestClassifier(max_features=3, max_samples=0.9), XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=300, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...), StackingClassifier(cv=3,
                   estimators=[('RF',
                                RandomForestClassifier(max_samples=0.9,
                                                       n_jobs=-1)),
                               ('knn', KNeighborsClassifier(n_jobs=-1))],
                   final_estimator=LogisticRegression(n_jobs=-1), n_jobs=-1,
                   passthrough=True)])

In [45]:
Database_website.train_data.fraud_bool.value_counts()

0    5542
1    5458
Name: fraud_bool, dtype: int64

In [46]:
label = ['fraud_bool']

In [53]:
Database_website.train_data.drop(label, axis=1).to_numpy()

array([[ 3.00000000e-01,  4.94457669e-02, -1.00000000e+00, ...,
         1.00000000e+00,  0.00000000e+00,  6.00000000e+00],
       [ 1.00000000e-01,  8.89359605e-01,  2.06000000e+02, ...,
         1.00000000e+00,  0.00000000e+00,  2.00000000e+00],
       [ 8.00000000e-01,  7.11778637e-01, -1.00000000e+00, ...,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [ 3.00000000e-01,  2.08949579e-01, -1.00000000e+00, ...,
         2.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 6.00000000e-01,  4.88259192e-01,  1.06000000e+02, ...,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.00000000e-01,  8.99380359e-01, -1.00000000e+00, ...,
         1.00000000e+00,  0.00000000e+00,  3.00000000e+00]])

In [55]:
Database_website.train_data[label].to_numpy()

array([[1],
       [0],
       [1],
       ...,
       [1],
       [1],
       [0]])